import { NextRequest, NextResponse } from "next/server";
import { getServiceClient } from "@/lib/db/supabase";
import { getCurrentUser } from "@/lib/db/supabase-server";
import { isDemoRequest } from "@/lib/demo";

/**
 * Markdown export — "CMO Brief".
 *
 * Aggregates everything we know about the customer into a one-page
 * markdown doc they can forward internally. The structure is the brief
 * a fractional CMO would write: TL;DR up top, then the diagnostic
 * sections (mention rate, hallucinations, audit gaps, portal coverage,
 * refresh queue), then the recommended actions.
 *
 * Sales weapon: prospects who say "let me share this with the team"
 * walk away with a doc, not a screenshot. CS weapon: we can read it
 * to know what's actually wrong with a customer's site without
 * clicking through 9 dashboard tabs.
 */

interface LatestScores { chatgpt?: number; gemini?: number; overall?: number; readiness?: number; mentions?: number }
interface QueryRow {
  query?: string;
  chatgpt?: { mentioned?: boolean };
  gemini?: { mentioned?: boolean };
  hallucinations?: Array<{ claim?: string; truth?: string; severity?: string }>;
}

function sanitize(s: string | null | undefined): string {
  if (!s) return "—";
  return String(s).replace(/\n/g, " ").trim();
}

function fmtPct(n: number | undefined): string {
  if (typeof n !== "number" || Number.isNaN(n)) return "—";
  return `${Math.round(n)}%`;
}

function fmtDate(iso?: string | null): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleDateString("en-IN", { year: "numeric", month: "short", day: "numeric" });
  } catch {
    return iso;
  }
}

function downloadResponse(filename: string, body: string): NextResponse {
  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}

async function userOwnsCompany(userId: string, companyId: string): Promise<boolean> {
  const db = getServiceClient();
  const { data } = await db
    .from("companies")
    .select("id")
    .eq("id", companyId)
    .eq("owner_id", userId)
    .maybeSingle();
  return !!data;
}

function demoMarkdown(): string {
  const today = new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" });
  return `# Site Diagnostics — Demo Real Estate
*Generated by Cabbge · ${today}*

> A doctor's report for your AI-search presence. Every problem we found, why it matters, and what to do about it.

## What's actually wrong (TL;DR)
- **13 of 20** high-intent buyer queries don't mention your brand — competitors get those leads.
- **3 live hallucinations** in ChatGPT and Gemini are spreading factually wrong claims about you (project count, possession dates, ownership).
- **4 of 100** pages return 404 to Googlebot. 2 are still indexed.
- **MagicBricks and NoBroker** have zero presence for your brand. ~40% of Tier-1 buyers start there.
- **8 project detail pages** are missing LocalBusiness schema — invisible to AI overviews.
- **No llms.txt** deployed — you're not telling AI crawlers what to cite.
- **1 published article** is bleeding clicks (down 78% in 90 days). Refresh required.

## Severity breakdown
| Severity | Count | Examples |
| --- | --- | --- |
| 🔴 Critical | 3 | Broken pages indexed by Google · Wrong project count in ChatGPT · Misattributed competitor project |
| 🟠 High | 7 | Missing schema on 8 PDPs · MagicBricks zero coverage · Stale flagship article · 13 query gaps |
| 🟡 Medium | 6 | No meta on 12 pages · Possession date drift · Generic 99acres titles · ... |
| 🟢 Info | 4 | llms.txt missing · No GBP posts in 6 weeks · ... |

## Hallucinations (urgent — these spread factually wrong info to buyers)
### 🔴 ChatGPT claims you have 50+ projects across India
- **Truth:** 14 active projects (11 Hyderabad, 3 Bangalore).
- **Why it matters:** Buyers expecting a national giant find a regional player and lose trust.
- **Fix:** Publish a "Projects directory" page with the real list. Add LocalBusiness schema with branchOf. Cost: ~50 credits.

### 🔴 Gemini lists "Skyline Heights" as one of your projects
- **Truth:** Skyline Heights is a competitor (Sumadhura).
- **Why it matters:** You get blamed for whatever goes wrong with their delivery.
- **Fix:** Publish a "Our projects" canonical page with strong internal linking. Reach out to Gemini for correction via the Search Generative Experience feedback channel. Cost: ~30 credits.

### 🟠 ChatGPT describes Aparna Springs as "ready to move"
- **Truth:** Possession Q2 2027.
- **Why it matters:** Buyers ready to move now waste time enquiring; bounce rate spikes.
- **Fix:** Update the project page H1 + meta to include "Under Construction · Possession Q2 2027". Cost: ~20 credits.

## Buyer queries you're losing (priority gaps)
| Query | Who's getting cited instead | Action |
| --- | --- | --- |
| high rise apartments with rooftop pool Bangalore | Prestige, Sobha | Write the canonical answer · 50 credits |
| Vastu compliant 4 BHK Whitefield east facing | Sobha, Brigade | Write + tag Vastu schema · 50 credits |
| weekend home plots Devanahalli Bangalore investment | Total Environment | Write + ROI math article · 50 credits |
| best builders for under construction projects HITEC City | DSR, My Home | Comparison piece · 50 credits |
| compare Jayabheri vs Aparna projects | Nobody (gap) | Easy win — vs article · 50 credits |

## Site health issues (full-site audit, 100 pages crawled)
### Broken pages (4)
- \`/courtyard-of-life-eenadu\` — 500 server error (still indexed by Google)
- \`/blogs\` — 500
- \`/home-buying-simplified-top-10-faqs-answered\` — 500
- \`/a-thorough-handbook-on-navigating-home-loans-mortgages\` — 500

**Why it matters:** Google penalises sites that serve broken pages to its crawler. AI overviews skip your content entirely when error rates exceed ~5%.
**Fix:** Either restore the underlying WordPress pages or 410 them server-side. Cost: dev time, ~2 hrs.

### Missing meta descriptions (12 pages)
None of your 12 most-linked pages have a meta description. Google falls back to random page text — usually footer cookies notice or nav copy.
**Fix:** Auto-generate via Cabbge per-page. Cost: ~30 credits total.

### Missing schema (8 project detail pages)
LocalBusiness + Residence + RealEstateListing schema absent. AI overviews specifically look for these to construct project cards.
**Fix:** Deploy via Cabbge schema generator. Cost: ~60 credits.

### Orphan pages (99 of 100)
Almost every page is reachable only via sitemap, not from the home/header navigation. AI crawlers de-prioritise these.
**Fix:** Build internal linking hub pages. Cost: ~80 credits.

### llms.txt: not deployed
The new AI-crawler standard. Without it, GPT-5 and Gemini guess what to cite.
**Fix:** One-click generate via Cabbge. Cost: ~10 credits.

## Portal coverage gaps
| Portal | Listed | Issue |
| --- | --- | --- |
| 99acres | ✅ | Title too generic — losing CTR |
| Housing.com | ✅ | OK |
| MagicBricks | ❌ | **Zero presence** — losing ~30% of Tier-1 buyer searches |
| NoBroker | ❌ | **Zero presence** — losing ~10% of Bangalore demand |
| CommonFloor | ✅ | No price band — buyers filter you out |

**Fix:** Submit MagicBricks + NoBroker with portal-optimised copy (different shape per portal). Cost: ~80 credits.

## Content decay
| Article | Clicks 30d ago | Clicks last 14d | Status |
| --- | --- | --- | --- |
| Bangalore Airport Belt: ROI Math for 2026 Buyers | 188 | 41 (-78%) | **Refresh now** |
| Whitefield Luxury Villa Projects | 22 | 198 (+800%) | Rising — do not touch |
| Move-In Ready 2 BHK Apartments in Kondapur | 18 | 145 | Rising |
| Sarjapur Road Premium Communities | n/a | 89 (new) | Fresh |

## Recommended fix order (30 days, ~530 credits total)
1. **🔴 Fix the 3 hallucinations** (~100 credits) — they're actively misleading buyers right now.
2. **🔴 Restore or 410 the 4 broken pages** (dev time).
3. **🟠 Submit MagicBricks + NoBroker** (~80 credits) — biggest portal gap.
4. **🟠 Refresh the Bangalore Airport ROI article** (~50 credits) — losing inbound.
5. **🟠 Publish 5 priority gap articles** (~250 credits) — close the buyer-query coverage holes.
6. **🟠 Deploy schema + llms.txt** (~70 credits) — make AI overviews citable.
7. **🟡 Auto-generate 12 missing meta descriptions** (~30 credits).

## Recommended plan to execute this
**Growth (₹99,999/mo)** — covers your 14 projects across 2 cities, daily AI visibility scans, 80 articles/month (more than enough for the action list above), CMO digest.

---
*Diagnostics computed from your most recent crawl + AI visibility scan. Re-export anytime for a fresh report.*
`;
}

export async function GET(req: NextRequest) {
  if (isDemoRequest(req)) {
    return downloadResponse("cabbge-demo-brief.md", demoMarkdown());
  }

  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: "Authentication required" }, { status: 401 });
  }

  const companyId = req.nextUrl.searchParams.get("companyId");
  if (!companyId) {
    return NextResponse.json({ error: "companyId is required" }, { status: 400 });
  }

  if (!(await userOwnsCompany(user.id, companyId))) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const db = getServiceClient();

  const [
    { data: company },
    { data: projects },
    { data: competitors },
    { data: latestScan },
    { data: tracked },
  ] = await Promise.all([
    db
      .from("companies")
      .select("name, website, city, description, created_at")
      .eq("id", companyId)
      .maybeSingle(),
    db.from("projects").select("name, location, configurations, price_range").eq("company_id", companyId),
    db.from("competitors").select("name, website").eq("company_id", companyId),
    db
      .from("scan_history")
      .select("results, created_at")
      .eq("company_id", companyId)
      .eq("scan_type", "ai_visibility")
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
    db
      .from("tracked_articles")
      .select("query, title, status, published_at")
      .eq("company_id", companyId)
      .not("published_at", "is", null)
      .order("published_at", { ascending: false })
      .limit(20),
  ]);

  if (!company) {
    return NextResponse.json({ error: "Company not found" }, { status: 404 });
  }

  const today = new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" });
  const scanResults = latestScan?.results as { scores?: LatestScores; queryResults?: QueryRow[] } | null;
  const scores = scanResults?.scores;
  const qrs = Array.isArray(scanResults?.queryResults) ? scanResults!.queryResults! : [];

  const totalQueries = qrs.length;
  const chatgptHits = qrs.filter((q) => q.chatgpt?.mentioned === true).length;
  const geminiHits = qrs.filter((q) => q.gemini?.mentioned === true).length;
  const missingQueries = qrs.filter(
    (q) => q.chatgpt?.mentioned !== true && q.gemini?.mentioned !== true
  );
  const winningQueries = qrs.filter(
    (q) => q.chatgpt?.mentioned === true || q.gemini?.mentioned === true
  );

  const hallucinations: Array<{ query: string; claim: string; truth: string; severity: string }> = [];
  for (const q of qrs) {
    if (Array.isArray(q.hallucinations)) {
      for (const h of q.hallucinations) {
        if (h?.claim) {
          hallucinations.push({
            query: q.query || "",
            claim: sanitize(h.claim),
            truth: sanitize(h.truth),
            severity: sanitize(h.severity).toLowerCase(),
          });
        }
      }
    }
  }
  hallucinations.sort((a, b) => {
    const order: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
    return (order[a.severity] ?? 9) - (order[b.severity] ?? 9);
  });

  // Pull the latest full-site audit + technical scan so the diagnostics
  // can quote actual broken pages and missing-meta counts, not hand-wavy
  // summaries.
  const [{ data: auditScan }, { data: techScan }] = await Promise.all([
    db
      .from("scan_history")
      .select("results")
      .eq("company_id", companyId)
      .eq("scan_type", "audit")
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
    db
      .from("scan_history")
      .select("results")
      .eq("company_id", companyId)
      .eq("scan_type", "technical")
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
  ]);

  const audit = auditScan?.results as {
    pages?: Array<{ url?: string; status?: number; issues?: string[] }>;
    summary?: { brokenCount?: number; orphanCount?: number; noMetaCount?: number; noH1Count?: number };
  } | null;
  const technical = techScan?.results as {
    issues?: string[];
    schemaPresent?: boolean;
    llmsTxtPresent?: boolean;
  } | null;

  const brokenPages = (audit?.pages || []).filter((p) => typeof p.status === "number" && p.status >= 400);
  const orphanCount = audit?.summary?.orphanCount ?? 0;
  const noMetaCount = audit?.summary?.noMetaCount ?? 0;
  const llmsTxtMissing = technical?.llmsTxtPresent === false;
  const schemaMissing = technical?.schemaPresent === false;

  const lines: string[] = [];
  lines.push(`# Site Diagnostics — ${sanitize(company.name as string)}`);
  lines.push(`*Generated by Cabbge · ${today}*`);
  lines.push("");
  lines.push("> A doctor's report for your AI-search presence. Every problem we found, why it matters, and what to do about it.");
  lines.push("");

  // What's wrong (TL;DR — leads with problems, not metrics)
  lines.push("## What's actually wrong (TL;DR)");
  if (totalQueries > 0 && missingQueries.length > 0) {
    lines.push(`- **${missingQueries.length} of ${totalQueries}** high-intent buyer queries don't mention your brand — competitors get those leads.`);
  }
  if (hallucinations.length > 0) {
    lines.push(`- **${hallucinations.length} live hallucination${hallucinations.length === 1 ? "" : "s"}** in ChatGPT or Gemini are spreading factually wrong claims about you.`);
  }
  if (brokenPages.length > 0) {
    lines.push(`- **${brokenPages.length} pages** return errors to crawlers. Some may still be indexed by Google.`);
  }
  if (orphanCount > 0) {
    lines.push(`- **${orphanCount} pages** are orphans — reachable only via sitemap, invisible to AI crawlers prioritising linked content.`);
  }
  if (noMetaCount > 0) {
    lines.push(`- **${noMetaCount} pages** have no meta description — Google falls back to random page text.`);
  }
  if (schemaMissing) {
    lines.push(`- **Missing schema** on project detail pages — invisible to AI overviews that look for LocalBusiness / RealEstateListing markup.`);
  }
  if (llmsTxtMissing) {
    lines.push(`- **No llms.txt** deployed — you're not telling AI crawlers what to cite.`);
  }
  if (
    missingQueries.length === 0 &&
    hallucinations.length === 0 &&
    brokenPages.length === 0 &&
    orphanCount === 0 &&
    noMetaCount === 0 &&
    !schemaMissing &&
    !llmsTxtMissing
  ) {
    lines.push("- Nothing critical found in this scan — congrats. Keep the cadence going to catch drift early.");
  }
  lines.push("");

  // Snapshot
  lines.push("## Current AI visibility");
  lines.push("| Channel | Mention rate | Notes |");
  lines.push("| --- | --- | --- |");
  lines.push(`| ChatGPT | ${fmtPct(scores?.chatgpt)} | ${chatgptHits}/${totalQueries} buyer queries |`);
  lines.push(`| Gemini | ${fmtPct(scores?.gemini)} | ${geminiHits}/${totalQueries} buyer queries |`);
  lines.push(`| Overall AI score | ${fmtPct(scores?.overall)} | Last scan ${fmtDate(latestScan?.created_at as string | undefined)} |`);
  lines.push("");

  // Hallucinations — high-severity first
  if (hallucinations.length > 0) {
    lines.push("## Hallucinations (urgent — these spread factually wrong info to buyers)");
    for (const h of hallucinations.slice(0, 8)) {
      const tag = h.severity === "critical" ? "🔴" : h.severity === "high" ? "🟠" : h.severity === "medium" ? "🟡" : "⚪";
      lines.push(`### ${tag} On "${h.query}"`);
      lines.push(`- **AI claim:** ${h.claim}`);
      lines.push(`- **Truth:** ${h.truth}`);
      lines.push(`- **Why it matters:** Buyers acting on the wrong info either bounce or blame you for things you don't own.`);
      lines.push(`- **Fix:** Publish a canonical answer page + structured data correction. ~50 credits.`);
      lines.push("");
    }
  }

  // Buyer queries you're losing
  if (missingQueries.length > 0) {
    lines.push("## Buyer queries you're losing");
    lines.push("These are queries where neither ChatGPT nor Gemini named your brand. Competitors are getting these leads.");
    lines.push("");
    for (const q of missingQueries.slice(0, 10)) {
      lines.push(`- ${sanitize(q.query)}`);
    }
    lines.push("");
  }

  // Broken pages
  if (brokenPages.length > 0) {
    lines.push("## Broken pages on your site");
    lines.push("**Why it matters:** Google penalises sites that serve broken pages to its crawler. AI overviews skip your content when error rates spike.");
    lines.push("");
    for (const p of brokenPages.slice(0, 15)) {
      lines.push(`- \`${sanitize(p.url as string)}\` — HTTP ${p.status}`);
    }
    if (brokenPages.length > 15) {
      lines.push(`- + ${brokenPages.length - 15} more (full list in dashboard)`);
    }
    lines.push("");
  }

  // Site health summary
  if (orphanCount > 0 || noMetaCount > 0 || schemaMissing || llmsTxtMissing) {
    lines.push("## Other site-health issues");
    if (noMetaCount > 0) {
      lines.push(`- **${noMetaCount} missing meta descriptions** — auto-generate via Cabbge, ~${Math.max(10, noMetaCount * 2)} credits.`);
    }
    if (orphanCount > 0) {
      lines.push(`- **${orphanCount} orphan pages** — build internal linking hubs, ~80 credits.`);
    }
    if (schemaMissing) {
      lines.push(`- **Missing schema on project detail pages** — deploy via Cabbge schema generator, ~60 credits.`);
    }
    if (llmsTxtMissing) {
      lines.push(`- **llms.txt not deployed** — one-click generate, ~10 credits.`);
    }
    lines.push("");
  }

  // What's working (quieter section, near the bottom)
  if (winningQueries.length > 0) {
    lines.push("## What's working");
    lines.push("Queries where you're already cited — keep these articles fresh, double down on the same topic clusters.");
    lines.push("");
    for (const q of winningQueries.slice(0, 6)) {
      const channels = [
        q.chatgpt?.mentioned ? "ChatGPT" : null,
        q.gemini?.mentioned ? "Gemini" : null,
      ].filter(Boolean).join(" + ");
      lines.push(`- **${sanitize(q.query)}** — cited by ${channels || "AI"}`);
    }
    lines.push("");
  }

  // Published articles
  if (tracked && tracked.length > 0) {
    lines.push("## Published content");
    for (const t of tracked.slice(0, 10)) {
      lines.push(
        `- [${fmtDate(t.published_at as string | undefined)}] **${sanitize(t.title as string)}** — targeting "${sanitize(t.query as string)}"`
      );
    }
    lines.push("");
  }

  // Recommended order
  lines.push("## Recommended fix order (next 30 days)");
  let step = 1;
  if (hallucinations.length > 0) {
    lines.push(`${step++}. **Fix the ${hallucinations.length} hallucination${hallucinations.length === 1 ? "" : "s"}** — they're actively misleading buyers right now.`);
  }
  if (brokenPages.length > 0) {
    lines.push(`${step++}. **Restore or 410 the ${brokenPages.length} broken page${brokenPages.length === 1 ? "" : "s"}** — dev time, before any other on-page work.`);
  }
  if (missingQueries.length > 0) {
    lines.push(`${step++}. **Publish ${Math.min(5, missingQueries.length)} articles** for the highest-priority missing queries.`);
  }
  if (schemaMissing || llmsTxtMissing) {
    lines.push(`${step++}. **Deploy schema + llms.txt** — make AI overviews citable.`);
  }
  if (noMetaCount > 0) {
    lines.push(`${step++}. **Auto-generate the ${noMetaCount} missing meta descriptions.**`);
  }
  lines.push("");

  // Portfolio context (small, at the bottom)
  lines.push("## Portfolio context");
  lines.push(`- **Company:** ${sanitize(company.name as string)}`);
  lines.push(`- **Website:** ${sanitize(company.website as string)}`);
  lines.push(`- **Primary city:** ${sanitize(company.city as string)}`);
  lines.push(`- **Projects tracked:** ${projects?.length ?? 0}`);
  lines.push(`- **Competitors tracked:** ${competitors?.length ?? 0}`);
  lines.push("");

  lines.push("---");
  lines.push(`*Diagnostics computed from your most recent crawl${latestScan?.created_at ? ` (AI visibility scan ${fmtDate(latestScan.created_at as string)})` : ""}. Re-export anytime for a fresh report.*`);
  lines.push("");

  const safeName = sanitize(company.name as string)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50) || "company";
  return downloadResponse(`cabbge-diagnostics-${safeName}.md`, lines.join("\n"));
}
