import { NextRequest, NextResponse } from "next/server";
import { getServiceClient } from "@/lib/db/supabase";
import { getCurrentUser } from "@/lib/db/supabase-server";
import { isDemoRequest } from "@/lib/demo";

/**
 * Markdown export — "CMO Brief".
 *
 * Aggregates everything we know about the customer into a one-page
 * markdown doc they can forward internally. The structure is the brief
 * a fractional CMO would write: TL;DR up top, then the diagnostic
 * sections (mention rate, hallucinations, audit gaps, portal coverage,
 * refresh queue), then the recommended actions.
 *
 * Sales weapon: prospects who say "let me share this with the team"
 * walk away with a doc, not a screenshot. CS weapon: we can read it
 * to know what's actually wrong with a customer's site without
 * clicking through 9 dashboard tabs.
 */

interface LatestScores { chatgpt?: number; gemini?: number; overall?: number; readiness?: number; mentions?: number }
interface QueryRow {
  query?: string;
  chatgpt?: { mentioned?: boolean };
  gemini?: { mentioned?: boolean };
  hallucinations?: Array<{ claim?: string; truth?: string; severity?: string }>;
}

function sanitize(s: string | null | undefined): string {
  if (!s) return "—";
  return String(s).replace(/\n/g, " ").trim();
}

function fmtPct(n: number | undefined): string {
  if (typeof n !== "number" || Number.isNaN(n)) return "—";
  return `${Math.round(n)}%`;
}

function fmtDate(iso?: string | null): string {
  if (!iso) return "—";
  try {
    return new Date(iso).toLocaleDateString("en-IN", { year: "numeric", month: "short", day: "numeric" });
  } catch {
    return iso;
  }
}

function downloadResponse(filename: string, body: string): NextResponse {
  return new NextResponse(body, {
    status: 200,
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control": "no-store",
    },
  });
}

async function userOwnsCompany(userId: string, companyId: string): Promise<boolean> {
  const db = getServiceClient();
  const { data } = await db
    .from("companies")
    .select("id")
    .eq("id", companyId)
    .eq("owner_id", userId)
    .maybeSingle();
  return !!data;
}

function demoMarkdown(): string {
  const today = new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" });
  return `# AI Visibility Brief — Demo Real Estate
*Generated by Cabbge · ${today}*

## TL;DR
Your brand is mentioned in **7 of 20** buyer queries on ChatGPT and **5 of 20** on Gemini. Three months ago that was 4/20 and 3/20 — directionally good, but five of your top six competitors still outrank you on "best premium developers in Hyderabad". Three live hallucinations need fact-fixes this week. Refresh queue: 4 articles below freshness threshold.

## Snapshot
| Metric | Now | 90 days ago | Δ |
| --- | --- | --- | --- |
| ChatGPT mention rate | 35% | 20% | **+15 pts** |
| Gemini mention rate | 25% | 15% | **+10 pts** |
| Average position when mentioned | #4 | #6 | +2 |
| Pages indexed by AI | 12 | 4 | +8 |
| Domain authority | 19 | 17 | +2 |

## Where you're winning
- "RERA approved builders in Hyderabad with possession 2026" — cited by both ChatGPT and Gemini, position #2.
- "best 3 BHK apartments in Gachibowli under 2 crore" — ChatGPT cites with positive sentiment.
- "luxury villa projects in Whitefield Bangalore" — gained a mention after the Whitefield Villa article (Mar 18).

## Where you're not (priority gaps)
1. **"high rise apartments with rooftop pool Bangalore"** — both AI engines cite competitors, none mention you. Article needed.
2. **"Vastu compliant 4 BHK Whitefield east facing"** — high-intent buyer query, zero brand mentions. Article needed.
3. **"weekend home plots Devanahalli Bangalore investment"** — emerging segment, no coverage at all.

## Hallucinations to fix this week
1. **ChatGPT** says you have 50+ projects across India. Truth: 14 active projects, 11 in Hyderabad, 3 in Bangalore. *Severity: High* — risks legal exposure if buyers act on it.
2. **Gemini** lists "Skyline Heights" as one of your projects. Truth: that's a competitor. *Severity: High*.
3. **ChatGPT** describes Aparna Springs as "ready to move". Truth: possession Q2 2027. *Severity: Medium*.

## Site health (full-site audit)
- 12 of 100 crawled pages have no meta description.
- 4 pages return 404. None linked from header but two indexed by Google.
- Schema missing on 8 project detail pages (LocalBusiness + Residence).
- llms.txt: not deployed. Recommended for GPT-5 era citation.

## Portal coverage
| Portal | Listed | Optimised |
| --- | --- | --- |
| 99acres | ✅ | ⚠️ Title too generic |
| Housing.com | ✅ | ✅ |
| MagicBricks | ❌ | — |
| NoBroker | ❌ | — |
| CommonFloor | ✅ | ⚠️ No price band |

## Refresh queue (4 articles)
1. *Bangalore Airport Belt: ROI Math for 2026 Buyers* — clicks 188 → 41 (-78%), 110d old. **Refresh now.**
2. *Whitefield Luxury Villa Projects* — 22 → 198 clicks (rising, do not refresh).
3. *Move-In Ready 2 BHK Apartments in Kondapur* — 18 → 145 (rising).
4. *Sarjapur Road Premium Communities* — fresh, no action.

## Recommended action plan (next 30 days)
1. **Publish 3 hallucination-fix articles.** Targets: project count, project ownership, possession dates. Cost: ~150 credits.
2. **Publish 4 new articles** for the priority gap queries. Cost: ~200 credits.
3. **Refresh the Bangalore Airport ROI article** — clicks falling, content stale. Cost: ~50 credits.
4. **Submit MagicBricks + NoBroker listings** with portal-optimised copy. Cost: ~80 credits.
5. **Deploy llms.txt + LocalBusiness schema** on the 8 project detail pages. Cost: ~60 credits.

## Recommended plan
**Growth (₹99,999/mo)** — fits 14 projects across 2 cities, daily AI visibility scans, 80 articles/mo, CMO digest.

---
*This brief was generated automatically from your most recent scan. Trends update on every scan; download a fresh copy any time.*
`;
}

export async function GET(req: NextRequest) {
  if (isDemoRequest(req)) {
    return downloadResponse("cabbge-demo-brief.md", demoMarkdown());
  }

  const user = await getCurrentUser();
  if (!user) {
    return NextResponse.json({ error: "Authentication required" }, { status: 401 });
  }

  const companyId = req.nextUrl.searchParams.get("companyId");
  if (!companyId) {
    return NextResponse.json({ error: "companyId is required" }, { status: 400 });
  }

  if (!(await userOwnsCompany(user.id, companyId))) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const db = getServiceClient();

  const [
    { data: company },
    { data: projects },
    { data: competitors },
    { data: latestScan },
    { data: tracked },
  ] = await Promise.all([
    db
      .from("companies")
      .select("name, website, city, description, created_at")
      .eq("id", companyId)
      .maybeSingle(),
    db.from("projects").select("name, location, configurations, price_range").eq("company_id", companyId),
    db.from("competitors").select("name, website").eq("company_id", companyId),
    db
      .from("scan_history")
      .select("results, created_at")
      .eq("company_id", companyId)
      .eq("scan_type", "ai_visibility")
      .order("created_at", { ascending: false })
      .limit(1)
      .maybeSingle(),
    db
      .from("tracked_articles")
      .select("query, title, status, published_at")
      .eq("company_id", companyId)
      .not("published_at", "is", null)
      .order("published_at", { ascending: false })
      .limit(20),
  ]);

  if (!company) {
    return NextResponse.json({ error: "Company not found" }, { status: 404 });
  }

  const today = new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" });
  const scanResults = latestScan?.results as { scores?: LatestScores; queryResults?: QueryRow[] } | null;
  const scores = scanResults?.scores;
  const qrs = Array.isArray(scanResults?.queryResults) ? scanResults!.queryResults! : [];

  const totalQueries = qrs.length;
  const chatgptHits = qrs.filter((q) => q.chatgpt?.mentioned === true).length;
  const geminiHits = qrs.filter((q) => q.gemini?.mentioned === true).length;
  const missingQueries = qrs.filter(
    (q) => q.chatgpt?.mentioned !== true && q.gemini?.mentioned !== true
  );
  const winningQueries = qrs.filter(
    (q) => q.chatgpt?.mentioned === true || q.gemini?.mentioned === true
  );

  const hallucinations: Array<{ query: string; claim: string; truth: string; severity: string }> = [];
  for (const q of qrs) {
    if (Array.isArray(q.hallucinations)) {
      for (const h of q.hallucinations) {
        if (h?.claim) {
          hallucinations.push({
            query: q.query || "",
            claim: sanitize(h.claim),
            truth: sanitize(h.truth),
            severity: sanitize(h.severity).toLowerCase(),
          });
        }
      }
    }
  }
  hallucinations.sort((a, b) => {
    const order: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };
    return (order[a.severity] ?? 9) - (order[b.severity] ?? 9);
  });

  const lines: string[] = [];
  lines.push(`# AI Visibility Brief — ${sanitize(company.name as string)}`);
  lines.push(`*Generated by Cabbge · ${today}*`);
  lines.push("");

  // TL;DR
  if (totalQueries > 0) {
    lines.push("## TL;DR");
    lines.push(
      `Your brand is mentioned in **${chatgptHits} of ${totalQueries}** buyer queries on ChatGPT and **${geminiHits} of ${totalQueries}** on Gemini. ${
        hallucinations.length > 0
          ? `${hallucinations.length} live hallucination${hallucinations.length === 1 ? "" : "s"} need fact-fixes this week. `
          : ""
      }${
        missingQueries.length > 0
          ? `${missingQueries.length} priority queries still have zero brand coverage.`
          : "Mention coverage looks healthy."
      }`
    );
    lines.push("");
  }

  // Snapshot
  lines.push("## Snapshot");
  lines.push("| Metric | Value |");
  lines.push("| --- | --- |");
  lines.push(`| ChatGPT mention rate | ${fmtPct(scores?.chatgpt)} |`);
  lines.push(`| Gemini mention rate | ${fmtPct(scores?.gemini)} |`);
  lines.push(`| Overall AI score | ${fmtPct(scores?.overall)} |`);
  lines.push(`| AI readiness | ${fmtPct(scores?.readiness)} |`);
  lines.push(`| Latest scan | ${fmtDate(latestScan?.created_at as string | undefined)} |`);
  lines.push("");

  // Portfolio
  lines.push("## Portfolio");
  lines.push(`- **Company:** ${sanitize(company.name as string)}`);
  lines.push(`- **Website:** ${sanitize(company.website as string)}`);
  lines.push(`- **Primary city:** ${sanitize(company.city as string)}`);
  lines.push(`- **Projects tracked:** ${projects?.length ?? 0}`);
  lines.push(`- **Competitors tracked:** ${competitors?.length ?? 0}`);
  lines.push("");

  // Where you're winning
  if (winningQueries.length > 0) {
    lines.push("## Where you're winning");
    for (const q of winningQueries.slice(0, 6)) {
      const channels = [
        q.chatgpt?.mentioned ? "ChatGPT" : null,
        q.gemini?.mentioned ? "Gemini" : null,
      ].filter(Boolean).join(" + ");
      lines.push(`- **${sanitize(q.query)}** — cited by ${channels || "AI"}.`);
    }
    lines.push("");
  }

  // Where you're not
  if (missingQueries.length > 0) {
    lines.push("## Where you're not (priority gaps)");
    for (const q of missingQueries.slice(0, 8)) {
      lines.push(`- ${sanitize(q.query)}`);
    }
    lines.push("");
  }

  // Hallucinations
  if (hallucinations.length > 0) {
    lines.push("## Hallucinations to fix this week");
    for (const h of hallucinations.slice(0, 8)) {
      lines.push(
        `- **${h.severity ? h.severity.toUpperCase() : "ISSUE"}** on "${h.query}" — claim: *${h.claim}* · truth: *${h.truth}*`
      );
    }
    lines.push("");
  }

  // Published articles
  if (tracked && tracked.length > 0) {
    lines.push("## Published content");
    for (const t of tracked.slice(0, 10)) {
      lines.push(
        `- [${fmtDate(t.published_at as string | undefined)}] **${sanitize(t.title as string)}** — targeting "${sanitize(t.query as string)}"`
      );
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*This brief was generated from scan_history${latestScan?.created_at ? ` captured ${fmtDate(latestScan.created_at as string)}` : ""}. Re-export anytime to get the latest numbers.*`);
  lines.push("");

  const safeName = sanitize(company.name as string)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50) || "company";
  return downloadResponse(`cabbge-brief-${safeName}.md`, lines.join("\n"));
}
